sudo: false
language: node_js
node_js:
- '8.12.0'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- yarn 
install:
- yarn install
script:
- yarn test
- yarn coveralls